In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier


df = pd.read_csv("dirty_data.csv")
df.head()

,no.,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder,AB.A.delta.a.FP1,AB.A.delta.b.FP2,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,1,M,57.0,2012.8.30,NaN,NaN,Addictive disorder,Alcohol use disorder,35.998557,21.717375,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,2,M,37.0,2012.9.6,6.0,120.0,Addictive disorder,Alcohol use disorder,13.425118,11.002916,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,3,M,32.0,2012.9.10,16.0,113.0,Addictive disorder,Alcohol use disorder,29.941780,27.544684,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,4,M,35.0,2012.10.8,18.0,126.0,Addictive disorder,Alcohol use disorder,21.496226,21.846832,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,5,M,36.0,2012.10.18,16.0,112.0,Addictive disorder,Alcohol use disorder,37.775667,33.607679,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662

In [43]:
knn_data = df.copy()
knn_data.head()

,no.,sex,age,eeg.date,education,IQ,main.disorder,specific.disorder,AB.A.delta.a.FP1,AB.A.delta.b.FP2,...,COH.F.gamma.o.Pz.p.P4,COH.F.gamma.o.Pz.q.T6,COH.F.gamma.o.Pz.r.O1,COH.F.gamma.o.Pz.s.O2,COH.F.gamma.p.P4.q.T6,COH.F.gamma.p.P4.r.O1,COH.F.gamma.p.P4.s.O2,COH.F.gamma.q.T6.r.O1,COH.F.gamma.q.T6.s.O2,COH.F.gamma.r.O1.s.O2
0,1,M,57.0,2012.8.30,NaN,NaN,Addictive disorder,Alcohol use disorder,35.998557,21.717375,...,55.989192,16.739679,23.452271,45.678820,30.167520,16.918761,48.850427,9.422630,34.507082,28.613029
1,2,M,37.0,2012.9.6,6.0,120.0,Addictive disorder,Alcohol use disorder,13.425118,11.002916,...,45.595619,17.510824,26.777368,28.201062,57.108861,32.375401,60.351749,13.900981,57.831848,43.463261
2,3,M,32.0,2012.9.10,16.0,113.0,Addictive disorder,Alcohol use disorder,29.941780,27.544684,...,99.475453,70.654171,39.131547,69.920996,71.063644,38.534505,69.908764,27.180532,64.803155,31.485799
3,4,M,35.0,2012.10.8,18.0,126.0,Addictive disorder,Alcohol use disorder,21.496226,21.846832,...,59.986561,63.822201,36.478254,47.117006,84.658376,24.724096,50.299349,35.319695,79.822944,41.141873
4,5,M,36.0,2012.10.18,16.0,112.0,Addictive disorder,Alcohol use disorder,37.775667,33.607679,...,61.462720,59.166097,51.465531,58.635415,80.685608,62.138436,75.888749,61.003944,87.455509,70.531662

In [44]:
knn_data_trim = knn_data.select_dtypes(include=[np.number])

In [45]:
knn_data_trim.isnull().sum()

no.                       0
age                       0
education                15
IQ                       13
AB.A.delta.a.FP1          0
                         ..
COH.F.gamma.p.P4.r.O1     0
COH.F.gamma.p.P4.s.O2     0
COH.F.gamma.q.T6.r.O1     0
COH.F.gamma.q.T6.s.O2     0
COH.F.gamma.r.O1.s.O2     0
Length: 1145, dtype: int64

In [46]:
knn_data_trim = knn_data_trim.fillna(knn_data_trim.mean())

In [47]:
knn_data_trim["education"].unique()

array([13.43870968,  6.        , 16.        , 18.        , 14.        ,
       12.        , 17.        , 13.        , 20.        , 15.        ,
        9.        , 11.        , 10.        ,  8.        ,  7.        ,
        1.        ,  0.        , 19.        ,  3.        ,  5.        ])

In [48]:
knn_data_trim["education"] = pd.cut(
    knn_data_trim["education"],
    bins=[0, 10, 15, 25],
    labels=[0, 1, 2]
)

In [49]:
knn_data_trim.isnull().sum()

no.                      0
age                      0
education                2
IQ                       0
AB.A.delta.a.FP1         0
                        ..
COH.F.gamma.p.P4.r.O1    0
COH.F.gamma.p.P4.s.O2    0
COH.F.gamma.q.T6.r.O1    0
COH.F.gamma.q.T6.s.O2    0
COH.F.gamma.r.O1.s.O2    0
Length: 1145, dtype: int64

In [50]:
knn_data_trim = knn_data_trim.fillna(knn_data_trim.mean(numeric_only=True))

In [51]:
knn_data_trim_15 = knn_data_trim.iloc[:, :15]

In [52]:
knn_data_trim_15.isnull().sum()

no.                 0
age                 0
education           2
IQ                  0
AB.A.delta.a.FP1    0
AB.A.delta.b.FP2    0
AB.A.delta.c.F7     0
AB.A.delta.d.F3     0
AB.A.delta.e.Fz     0
AB.A.delta.f.F4     0
AB.A.delta.g.F8     0
AB.A.delta.h.T3     0
AB.A.delta.i.C3     0
AB.A.delta.j.Cz     0
AB.A.delta.k.C4     0
dtype: int64

In [53]:
print(knn_data_trim.shape)
print(knn_data_trim_15.shape)

(945, 1145)
(945, 15)

In [59]:
knn_data_trim_15 = knn_data_trim_15.dropna(subset=["education"])

In [60]:
X = knn_data_trim_15.drop("education", axis=1)
y = knn_data_trim_15["education"]

X.shape

(943, 14)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((754, 14), (189, 14), (754,), (189,))

In [62]:
y.isnull().sum()

np.int64(0)

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

In [73]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.5873015873015873

In [74]:
metrics.confusion_matrix(y_test, y_pred)

array([[ 2,  8,  1],
       [10, 96, 20],
       [ 0, 39, 13]])

In [75]:
metrics.classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.17      0.18      0.17        11\n           1       0.67      0.76      0.71       126\n           2       0.38      0.25      0.30        52\n\n    accuracy                           0.59       189\n   macro avg       0.41      0.40      0.40       189\nweighted avg       0.56      0.59      0.57       189\n'

In [76]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.17      0.18      0.17        11
           1       0.67      0.76      0.71       126
           2       0.38      0.25      0.30        52

    accuracy                           0.59       189
   macro avg       0.41      0.40      0.40       189
weighted avg       0.56      0.59      0.57       189